---
# Database server specific variables

db_user: postgres
db_group: postgres
db_data_dir: /var/lib/postgresql/14/main
db_config_dir: /etc/postgresql/14/main

# PostgreSQL configuration
postgresql_version: "14"
postgresql_listen_addresses: ['localhost']
postgresql_port: 5432
postgresql_max_connections: 100
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "1GB"

# Database users and databases
postgresql_databases:
  - name: app_production
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

postgresql_users:
  - name: app_user
    password: "{{ vault_postgresql_app_password }}"
    databases: [app_production]
    priv: "ALL"

# Backup configuration
postgresql_backup_enabled: true
postgresql_backup_dir: /var/backups/postgresql
postgresql_backup_retention: 7