---
# Monitoring server specific variables

monitoring_user: prometheus
monitoring_group: prometheus

# Prometheus configuration
prometheus_version: "2.45.0"
prometheus_port: 9090
prometheus_data_retention: "15d"

# Grafana configuration
grafana_version: "9.5.2"
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# Node exporter configuration
node_exporter_version: "1.6.0"
node_exporter_port: 9100

# Alerting configuration
alertmanager_enabled: true
alertmanager_version: "0.25.0"
alertmanager_port: 9093