---
- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: [nodejs, repository]

- name: Add NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_os_family == "Debian"
  tags: [nodejs, repository]

- name: Install Node.js
  apt:
    name:
      - nodejs
    state: present
  when: ansible_os_family == "Debian"
  tags: [nodejs, install]

- name: Install Node.js (RedHat)
  yum:
    name: nodejs
    state: present
  when: ansible_os_family == "RedHat"
  tags: [nodejs, install]

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ npm_global_packages | default([]) }}"
  tags: [nodejs, npm]