---
- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload ufw
  command: ufw reload
  when: ansible_os_family == "Debian"