---
- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /bin/false
    home: /nonexistent
    comment: "Prometheus monitoring system"
  tags: [prometheus, user]

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
  tags: [prometheus, directories]

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    checksum: "sha256:{{ prometheus_checksum | default(omit) }}"
  tags: [prometheus, download]

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes
    extra_opts: ["--strip-components=1"]
  tags: [prometheus, extract]

- name: Install Prometheus binaries
  copy:
    src: "/tmp/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  tags: [prometheus, install]

- name: Install Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart prometheus
  tags: [prometheus, config]

- name: Create Prometheus service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags: [prometheus, service]

- name: Ensure Prometheus is running and enabled
  service:
    name: prometheus
    state: started
    enabled: yes
  tags: [prometheus, service]