---
- name: Deploy application stack
  hosts: application
  become: true
  vars_files:
    - ../group_vars/all.yml

  pre_tasks:
    - name: Check application requirements
      fail:
        msg: "Application deployment requires Docker role"
      when: "'docker' not in ansible_facts.packages"

  roles:
    - role: docker
      tags: [application, docker]

    - role: nodejs
      tags: [application, nodejs]

  tasks:
    - name: Create application directory
      file:
        path: "{{ deploy_path }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      tags: [application, setup]

    - name: Deploy application configuration
      template:
        src: application.config.j2
        dest: "{{ deploy_path }}/config.json"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
      tags: [application, config]

    - name: Deploy application code
      copy:
        src: "../files/app/"
        dest: "{{ deploy_path }}/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      tags: [application, code]

    - name: Build Docker image
      docker_image:
        name: "{{ app_name }}"
        build:
          path: "{{ deploy_path }}"
        source: build
        state: present
      tags: [application, docker]

    - name: Run application container
      docker_container:
        name: "{{ app_name }}"
        image: "{{ app_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:{{ app_port }}"
        env:
          NODE_ENV: "{{ environment }}"
      tags: [application, docker]

    - name: Wait for application to be ready
      uri:
        url: "http://localhost:{{ app_port }}{{ app_health_check }}"
        method: GET
        status_code: 200
        timeout: 30
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 5
      tags: [application, healthcheck]